### ISSUE TITLE
Vercel deploy error 

### ISSUE THREAD

**Issue by veronini** [veronini/dev4-make-it-personal#2]
https://github.com/veronini/dev4-make-it-personal/blob/ff345de23aad1f2c5c038f849a08d3171de20e6d/client/pages/tickets/%5Bid%5D.js#L39

Bij het deployen op Vercel krijg ik de error "data.map is not a function",  "error Command failed with exit code 1."  &  "Error: Command "yarn run build" exited with 1" .

Ik heb geprobeerd de data in een array te zetten, de folder next te verwijderen en nog andere "oplossingen" van stackoverflow maar niets werkt. 

De "ticket" die in de functie word gebruikt voor de path is dan ook undefined bij het deployen. Lokaal werkt alles wel!

**Comment by SimonVanherweghe** [comment]
Ok, beetje moeilijk zonder de volledige vercel log, mijn gok:

Als data.map geen functie is, dan zal data geen array zijn.
Als data geen array is, dan is er wss iets mis gelopen bij het fetchen van de data. Ben je zeker dat jouw environment variabele goed ingesteld staat? `process.env.NEXT_PUBLIC_STRAPI_URL`
